language: php
php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  - TYPO3=TYPO3_8-0 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=TYPO3_8-1 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=TYPO3_8-2 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=TYPO3_8-3 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=TYPO3_8-4 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=TYPO3_8-5-0 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
  - TYPO3=master REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

  include:
    # TYPO3 7.6
    - php: 5.6
      env: TYPO3=TYPO3_7-6 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
    - php: 7.0
      env: TYPO3=TYPO3_7-6 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
    - php: 7.1
      env: TYPO3=TYPO3_7-6 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
    - php: nightly
      env: TYPO3=TYPO3_7-6 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes
    - php: hhvm
      env: TYPO3=TYPO3_7-6 REPO="rest" CLI_HOME=`pwd` DB=mysql UNIT_TESTS=yes FUNCTIONAL_TESTS=yes

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a4154f7992654c2bb540
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_script:
  # We don't need xdebug right now
  - phpenv config-rm xdebug.ini
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export CHECK_MYSQL_CREDENTIALS="no";
    bash Build/install.sh;
  # Create the database "typo3" if it does not exist
  - mysql -e 'CREATE DATABASE IF NOT EXISTS typo3;'
  # Remove the local PHPUnit so it doesn't get mixed up with the one from TYPO3 core
  - composer remove phpunit/phpunit --dev

script:
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export CHECK_MYSQL_CREDENTIALS="no";
    export MANUAL_TESTS="no";
    bash Build/test.sh;