language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=master INTEGRATION=master
  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_7-3 INTEGRATION=master
  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_7-0 INTEGRATION=master
  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_6-2 INTEGRATION=master
#  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_6-1 INTEGRATION=master
#  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_6-0 INTEGRATION=master
#  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_4-7 INTEGRATION=TYPO3_4-7
#  - VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7

matrix:
  allow_failures:
    - php: 5.3
    - php: nightly
    - php: hhvm

  include:
    - php: 5.3
      env: VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_6-2 INTEGRATION=master
    - php: 5.4
      env: VENDOR="cundd" REPO="rest" CLI_HOME=`pwd` DB=mysql TYPO3=TYPO3_6-2 INTEGRATION=master

sudo: false

before_script:
# Install build dependencies

# TODO: The LocalConfiguration.php is only available for TYPO3 6.0 and higher.
# To support lower versions we have to deliver also a localconf file
#  - cd ..
#  - git clone --single-branch --branch $INTEGRATION --depth 1 https://github.com/Konafets/TYPO3-Travis-Integration build-environment
#  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
#  - source build-environment/install-helper.sh
#  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
#  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - >
    ls -hal;
    ls -hal ..;
    cd ..;
    echo "Get TYPO3 source";
    git clone --single-branch --branch $TYPO3 --depth 1 git://git.typo3.org/Packages/TYPO3.CMS.git;
    cd TYPO3.CMS;
    composer install;
    cd ..;

  - >
    echo "Put target into ext folder";
    mkdir -p TYPO3.CMS/typo3conf/ext;
    mv $REPO TYPO3.CMS/typo3conf/ext/;
    #git clone --single-branch --branch develop --depth 1 https://github.com/$VENDOR/$REPO typo3conf/ext/$REPO/;
    cd TYPO3.CMS/typo3conf/ext/$REPO/;

  - >
    echo "Install dependencies";
    composer --version;
    COMPOSER=cundd_composer.json composer install --verbose;
    cd ../../../;
    mysql -e 'create database typo3_test;';

script:
  #- $CLI_HOME/ext-phpunit/vendor/bin/phpcs --standard=TYPO3CMS --ignore=PEAR --warning-severity=0 --extensions=php,inc -sv $CLI_HOME/ext-phpunit
  #- find -L ext-phpunit -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # - php $CLI_HOME/typo3/cli_dispatch.phpsh phpunit typo3conf/ext/$REPO/Tests/Unit
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    ls -hal .;
    ls -hal ./typo3conf/ext/rest/Tests/*;
    find ./typo3conf/ext/rest/Tests/Functional -path '*Test.php' -print;
    find ./typo3conf/ext/rest/Tests/Functional -path '*Test.php' -exec ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {} \; ;
