language: php
php:
  - "7.3"
  - "7.4"
  - "8.0"
  - "nightly"

env:
  - TYPO3=^9.5 DB=mysql
  - TYPO3=^10.4 DB=mysql

jobs:
  fast_finish: true
  allow_failures:
    - php: "8.0"
    - php: nightly
    - php: hhvm
    - env: TYPO3=~11.0 DB=mysql
    - env: TYPO3=dev-master DB=mysql

  include:
    - php: "7.2"
      env: TYPO3=^9.5 DB=mysql
    - php: "7.4"
      env: TYPO3=~11.0 DB=mysql
    - php: "8.0"
      env: TYPO3=~11.0 DB=mysql
    - php: "7.4"
      env: TYPO3=dev-master DB=mysql
    - php: "8.0"
      env: TYPO3=dev-master DB=mysql

services:
  - mysql

os: linux

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a4154f7992654c2bb540
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  # We don't need xdebug right now
  - phpenv config-rm xdebug.ini || echo "xdebug.ini not removed";

before_script:
  #  - if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then mysql -e "CREATE DATABASE typo3;"; fi
  #  - if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then mysql -e "GRANT ALL PRIVILEGES ON typo3.* to travis@'%';"; fi
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="127.0.0.1";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";

  # Downgrade doctrine/dbal to 2.11 on v10 and v11 (see https://github.com/Nimut/testing-framework/issues/136)
  - if [[ "$TYPO3" == "^10.4" || "$TYPO3" == "~11.0" ]]; then composer require "doctrine/dbal:2.11" --no-update; fi

  - composer require typo3/minimal=$TYPO3 --no-update;
  - composer update;

  #    bash Build/install.sh;
  ## Remove the local PHPUnit so it doesn't get mixed up with the one from TYPO3 core
  #- composer remove phpunit/phpunit --dev && composer update

script:
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="127.0.0.1";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export CHECK_MYSQL_CREDENTIALS="no";
    export MANUAL_TESTS="no";
    bash Build/test.sh -- -v;
